baseURL: https://rgeraskin.com/
title: DevOps Blog
theme: aether
# googleAnalytics: "Your google analytics tracking ID - optional"
# disqusShortname: "Your shortname for Disqus - optional"

DefaultContentLanguage: ru
# do not turn it off: language navs'll be broken
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 2
    languageCode: en-en
  ru:
    languageName: Russian
    contentDir: content/ru
    weight: 1
    languageCode: ru

params:
  brand: rgeraskin@blog
  description: Random thoughts about DevOps and IT
  # homeimg: Path, within the 'assets' folder, of the image used for the home button at the bottom of each post - optional
  # bgimg: Path, within the 'assets' folder, of the image used for the page background - optional
  # rssinmenu = whether you would like a RSS feed link to appear in the navigation menu (true, false) - optional

markup:
  highlight:
    style: igor
